package mknote

import (
	"github.com/rpajarola/exiftools/models"
)

// Useful resources used in creating these tables:
//    http://www.exiv2.org/makernote.html
//    http://www.exiv2.org/tags-canon.html
//    http://www.exiv2.org/tags-nikon.html

// Known Maker Note fields
const (
	// common fields
	ISOSpeed                   models.FieldName = "ISOSpeed"
	ColorMode                  models.FieldName = "ColorMode"
	Quality                    models.FieldName = "Quality"
	Sharpening                 models.FieldName = "Sharpening"
	Focus                      models.FieldName = "Focus"
	FlashSetting               models.FieldName = "FlashSetting"
	FlashDevice                models.FieldName = "FlashDevice"
	WhiteBalanceBias           models.FieldName = "WhiteBalanceBias"
	WBRBLevels                 models.FieldName = "WBRBLevels"
	ProgramShift               models.FieldName = "ProgramShift"
	ExposureDiff               models.FieldName = "ExposureDiff"
	ISOSelection               models.FieldName = "ISOSelection"
	DataDump                   models.FieldName = "DataDump"
	Preview                    models.FieldName = "Preview"
	FlashComp                  models.FieldName = "FlashComp"
	ISOSettings                models.FieldName = "ISOSettings"
	ImageBoundary              models.FieldName = "ImageBoundary"
	FlashExposureComp          models.FieldName = "FlashExposureComp"
	FlashBracketComp           models.FieldName = "FlashBracketComp"
	ExposureBracketComp        models.FieldName = "ExposureBracketComp"
	ImageProcessing            models.FieldName = "ImageProcessing"
	CropHiSpeed                models.FieldName = "CropHiSpeed"
	ExposureTuning             models.FieldName = "ExposureTuning"
	SerialNumber               models.FieldName = "SerialNumber"
	ImageAuthentication        models.FieldName = "ImageAuthentication"
	ActiveDLighting            models.FieldName = "ActiveDLighting"
	VignetteControl            models.FieldName = "VignetteControl"
	ImageAdjustment            models.FieldName = "ImageAdjustment"
	ToneComp                   models.FieldName = "ToneComp"
	AuxiliaryLens              models.FieldName = "AuxiliaryLens"
	LensType                   models.FieldName = "LensType"
	Lens                       models.FieldName = "Lens"
	FocusDistance              models.FieldName = "FocusDistance"
	DigitalZoom                models.FieldName = "DigitalZoom"
	FlashMode                  models.FieldName = "FlashMode"
	ShootingMode               models.FieldName = "ShootingMode"
	AutoBracketRelease         models.FieldName = "AutoBracketRelease"
	LensFStops                 models.FieldName = "LensFStops"
	ContrastCurve              models.FieldName = "ContrastCurve"
	ColorHue                   models.FieldName = "ColorHue"
	SceneMode                  models.FieldName = "SceneMode"
	HueAdjustment              models.FieldName = "HueAdjustment"
	NEFCompression             models.FieldName = "NEFCompression"
	NoiseReduction             models.FieldName = "NoiseReduction"
	LinearizationTable         models.FieldName = "LinearizationTable"
	RawImageCenter             models.FieldName = "RawImageCenter"
	SensorPixelSize            models.FieldName = "SensorPixelSize"
	SceneAssist                models.FieldName = "SceneAssist"
	RetouchHistory             models.FieldName = "RetouchHistory"
	ImageDataSize              models.FieldName = "ImageDataSize"
	ImageCount                 models.FieldName = "ImageCount"
	DeletedImageCount          models.FieldName = "DeletedImageCount"
	ShutterCount               models.FieldName = "ShutterCount"
	ImageOptimization          models.FieldName = "ImageOptimization"
	SaturationText             models.FieldName = "SaturationText"
	VariProgram                models.FieldName = "VariProgram"
	ImageStabilization         models.FieldName = "ImageStabilization"
	AFResponse                 models.FieldName = "AFResponse"
	HighISONoiseReduction      models.FieldName = "HighISONoiseReduction"
	ToningEffect               models.FieldName = "ToningEffect"
	PrintIM                    models.FieldName = "PrintIM"
	CaptureData                models.FieldName = "CaptureData"
	CaptureVersion             models.FieldName = "CaptureVersion"
	CaptureOffsets             models.FieldName = "CaptureOffsets"
	ScanIFD                    models.FieldName = "ScanIFD"
	ICCProfile                 models.FieldName = "ICCProfile"
	CaptureOutput              models.FieldName = "CaptureOutput"
	Panorama                   models.FieldName = "Panorama"
	ImageType                  models.FieldName = "ImageType"
	FirmwareVersion            models.FieldName = "FirmwareVersion"
	FileNumber                 models.FieldName = "FileNumber"
	OwnerName                  models.FieldName = "OwnerName"
	CameraInfo                 models.FieldName = "CameraInfo"
	CustomFunctions            models.FieldName = "CustomFunctions"
	ModelID                    models.FieldName = "ModelID"
	PictureInfo                models.FieldName = "PictureInfo"
	ThumbnailImageValidArea    models.FieldName = "ThumbnailImageValidArea"
	SerialNumberFormat         models.FieldName = "SerialNumberFormat"
	SuperMacro                 models.FieldName = "SuperMacro"
	OriginalDecisionDataOffset models.FieldName = "OriginalDecisionDataOffset"
	WhiteBalanceTable          models.FieldName = "WhiteBalanceTable"
	LensModel                  models.FieldName = "LensModel"
	InternalSerialNumber       models.FieldName = "InternalSerialNumber"
	DustRemovalData            models.FieldName = "DustRemovalData"
	ProcessingInfo             models.FieldName = "ProcessingInfo"
	MeasuredColor              models.FieldName = "MeasuredColor"
	VRDOffset                  models.FieldName = "VRDOffset"
	SensorInfo                 models.FieldName = "SensorInfo"
	ColorData                  models.FieldName = "ColorData"
)
